name: eyed_client
description: "EyeD Iris Recognition Client"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  flutter_riverpod: ^2.6.1
  go_router: ^14.8.1
  dio: ^5.7.0
  web_socket_channel: ^3.0.1
  flutter_webrtc: ^0.12.9
  json_annotation: ^4.9.0
  collection: ^1.19.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.14
  json_serializable: ^6.9.4

flutter:
  generate: true
  uses-material-design: true
